### PR TITLE
WIP: Issue #97 prerequisites guidance

### PR DESCRIPTION
**Pull request by rolfedh**

### CODE REVIEW

**Comment by rolfedh** [comment]
https://github.com/redhat-documentation/modular-docs/issues/97

**Comment by IngridT1** [comment]
@rolfedh I like this FAQ that you're putting together. Nice start.

**Comment by rolfedh** [comment]
I'm closing this pull request because I feel like the advice it contains is off-track. I'll start over with a smaller simpler PR to address issue #97

**Comment by rolfedh** [comment]
Closing

**Pull request closed without merging**
