### PR TITLE
Update CONTRIBUTING.md with forking instructions

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes https://github.com/redhat-documentation/modular-docs/issues/225

### CODE REVIEW

**Comment by mjahoda** [comment]
Hi @rolfedh, In addition to my comment regarding the screenshots, I would also add some steps that encourage contributors to work on a refreshed repository, for example:
https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/create_or_edit_content.adoc#ensure-your-local-repository-is-in-sync-with-the-remote

**Review by Jenny-Anne — COMMENTED** [review]
Hi Rolfe, thanks for making the update. 

For completeness, Mirek's suggestion to keep the local repo up-to-date by doing a `git pull` or similar command before creating a branch seems good, maybe before Step 1 in the Contributing Changes section? 

Otherwise, LGTM.

**Comment by rolfedh** [comment]
> my comment regarding the screenshots

Thanks, Mirek. Your comments aren't visible, yet. Is your review marked "pending"?

**Review by mjahoda — COMMENTED** [review]
I provided two suggestions (one inline, the second as a comment on the PR page).

**Comment by rolfedh** [comment]
Obsolete. See https://github.com/redhat-documentation/modular-docs/pull/230 instead.

**Comment by rolfedh** [comment]
Thanks @mjahoda and @Jenny-Anne. I've applied your suggestions and pushed them to https://github.com/redhat-documentation/modular-docs/pull/230 instead.

**Pull request closed without merging**
