### PR TITLE
Update nested assemblies diagrams.

### PR DESCRIPTION
**Pull request by sterobin**
Addresses issue #110 . See [section preview](http://file.rdu.redhat.com/~sterobin/modular-docs-manual/master.html#nesting-assemblies) (requires VPN).

I ended up foregoing the Asciidoctor Diagram option because it was proving to be too cumbersome and limited, also unattractive. I instead just designed a simple diagram illustration in LibreOffice and included both the ODT source files and the final PNG files in the repo, so we don't run into this issue again.

### CODE REVIEW

**Review by rkratky — APPROVED** [review]
LGTM, but I'd suggest using a monospace font.

**Comment by sterobin** [comment]
@rkratky , good point. Done. Now monospaced. Thanks!

**Review by mikemckiernan — APPROVED** [review]
/lgtm, a picture is worth a thousand words.

**Comment by mjahoda** [comment]
Looks fine.

**Review by mjahoda — APPROVED** [review]
Looks fine.

**Review by Levi-Le — APPROVED** [review]

**Comment by yzimmerm** [comment]
Hi!

How do I see the diagram? It seems that all links lead to the github issue.

Yehuda Zimmerman, RHCSA

Technical Writer III

Red Hat EMEA <https://www.redhat.com/>

***@***.***
M: +972-50-942-1156     IM: yzimmerm
<https://red.ht/sig>

**Comment by sterobin** [comment]
@yzimmerm , preview link in the description.

**Comment by yzimmerm** [comment]
Which one? They all seemed to take me to git hub.

Yehuda Zimmerman, RHCSA

Technical Writer III

Red Hat EMEA <https://www.redhat.com/>

***@***.***
M: +972-50-942-1156     IM: yzimmerm
<https://red.ht/sig>

**Review by yzimmerm — APPROVED** [review]
LGTM

**Review by fbolton — APPROVED** [review]
LGTM - the diagrams illustrate this technique perfectly.

I mention in passing that this technique only works for assembly nesting that is one level deep. But this is already a known issue, and lies outside the scope of this particular update.

**Comment by sterobin** [comment]
@fbolton Right, understood. Thanks!

**Review by neal-timpe — APPROVED** [review]

**Review by thatdocslady — APPROVED** [review]
LGTM!

**Pull request merged**
