### PR TITLE
On Hold: issue-135 Change format of Additional Resources/Next Steps to bulleted links only in the templates

### PR DESCRIPTION
**Pull request by emmurphy1**
[Issue 135](https://github.com/redhat-documentation/modular-docs/issues/135)

### CODE REVIEW

**Review by sterobin — APPROVED** [review]
@emmurphy1 Agreed, and approved. I've found this to be best anyway personally, and if anytime you need to give additional context to the link you're providing, often it is an indication that you might need to provide that link directly in the content. But then that too is often discouraged from mod docs perspective, but even so, the vast majority of the cases you can still get away with just a link in the additional resources and it's still understandable and consistent.

**Review by rolfedh — APPROVED** [review]

**Review by ncbaratta — APPROVED** [review]
LGTM

**Comment by emmurphy1** [comment]
On hold pending the outcome of this ticket:
https://projects.engineering.redhat.com/browse/CCS-4121

**Comment by emmurphy1** [comment]
The review board decided that this is a style issue and should be left to individual writers. In addition, lists of links without context can be problematic from an accessibility POV. I am closing this PR without merging.

**Pull request closed without merging**
