### PR TITLE
Recommendation to use second level heading syntax for assembly-level prerequisites

### LINKED ISSUE #124: Issues with the assembly-level prerequisites heading
This issue originated in https://github.com/redhat-documentation/modular-docs/issues/97 but deserves its own separate issue.

After discussing this with @kalexand-rh, I have a better understanding of the item @ncbaratta mentioned. Although it deserves fuller discussion, here is the issue in summary:

Currently, `.Prerequisite` appears in both TEMPLATE_ASSEMBLY_a-collection-of-modules.adoc and TEMPLATE_PROCEDURE_doing-one-procedure.adoc.

The problem is that, in TEMPLATE_ASSEMBLY_a-collection-of-modules.adoc, `.Prerequisite` is inconsistent with `== Additional resources (or Next steps)`.

Changing `.Prerequisites` to `== Prerequisites` would do the following:

- Eliminate a style inconsistency.
- Make it clear that the prerequisites apply to all of the modules, not just the first one. (With `.Prerequisites`, it's unclear what the scope of the prerequisites is. One possible interpretation is that it applies only to the first module instead of all of them.)
- Enable "Prerequisites" for assemblies near the top of the content hierarchy to show up in the TOC.

Issue https://github.com/redhat-documentation/modular-docs/issues/97 also discusses arguments against making this change. I thought it would be important to take a more complete look at the proposed change so we could have a more nuanced discussion of its benefits and drawbacks. I'll be glad to describe the issue in more detail at an upcoming meeting. 

For an example of what the current assembly-level `.Prerequisites` looks like in our documentation, please see: https://docs.openshift.com/container-platform/4.5/installing/installing_aws/installing-aws-default.html

### PR DESCRIPTION
**Pull request by Preeticp**
This issue fixes #124 as per discussions with the team and as per comments on the issue.

### CODE REVIEW

**Comment by Preeticp** [comment]
@rkratky @sterobin @emmurphy1 @theashiot can you all please review this PR. Thank you!

**Review by rolfedh — APPROVED** [review]

**Review by sterobin — APPROVED** [review]
@Preeticp Good with me for the reasons we've discussed on the call, though I got the sense that we still don't have a majority agreement yet. Will see if we can get enough approvals here. Thanks for this!

**Review by oraNod — APPROVED** [review]
@Preeticp good suggestion IMO

**Review by theashiot — APPROVED** [review]

**Review by rkratky — APPROVED** [review]

**Review by kalexand-rh — COMMENTED** [review]
LGTM!

**Review by naciao — APPROVED** [review]

**Comment by mrksu** [comment]
I've updated the assembly template in `newdoc` to match this change. Commit: https://github.com/redhat-documentation/newdoc/commit/9e271823a556de55d7d7ac3df789dc10081a800c 

The updated template is available in `newdoc` version 2.6.1, which I'm now releasing.

**Pull request merged**
