### PR TITLE
Changes to templates and other files re #19

### PR DESCRIPTION
**Pull request by tradej**
I have made some further changes to #19 that I think should be incorporated:

* The templates now contain the reusable IDs and the comment section. I think it is valuable to promote using `:context` even where not strictly necessary because upon reuse, the ID of the module does not change, therefore we don't break existing links.
* I have changed the IDs in the existing source files to incorporate the new guidelines.

Questions:

* Should I also rename the templates? They use underscores instead of dashes now. I'm afraid I could break some external links if there are any, though.

### CODE REVIEW

**Comment by rkratky** [comment]
> Should I also rename the templates? They use underscores instead of dashes now. I'm afraid I could break some external links if there are any, though.

Yes. Better to break them now than later.

**Comment by tradej** [comment]
OK. I will do that after lunch.

**Comment by tradej** [comment]
Renamed. The PR is ready for review and merging, unless you have further comments or requests.

**Comment by sterobin** [comment]
@tradej, I assume you don't need my signoff at this point for this, but in case you do and I don't realize, the anchor name changes, etc., look good to me. You're good to merge with #19 if @rkratky is good with it.

**Pull request merged**
