### PR TITLE
Double quotes in templates and content

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Single quotes are [intended](https://github.com/asciidoctor/asciidoctor/issues/2960) to provide [character substitutions](https://asciidoctor.org/docs/user-manual/#attribute-list-substitutions) and thus a wrong choice for IDs. This PR changes all single quotes in IDs to double quotes. There is no change to text and meaning, only the internals are technically correct after this change.

### CODE REVIEW

**Comment by kalexand-rh** [comment]
@adahms, what do you think? This could fix https://github.com/redhat-documentation/modular-docs/issues/87.

**Comment by adahms** [comment]
Thanks for the ping, @kalexand-rh!

I agree - the changes in this PR appear to address the central concern in that issue, and there are no outstanding instances of ' after these changes go through.

Looks good to me - you're welcome to merge if you like, but I can see there are some conflicts given the work that took place in between, and I can go through and resolve and merge those if you'd prefer. :)

**Comment by kalexand-rh** [comment]
@adahms, it depends on what your preferred workflow is. I don't have access to resolve the conflicts in the UI, but I'm happy to create a new PR based on @VladimirSlavik's changes and that addresses the conflicts.

**Comment by adahms** [comment]
@kalexand-rh - Resolved conflicts from the CLI and merged.

Closing PR.

**Comment by VladimirSlavik** [comment]
Thank you!

**Pull request merged**
