### PR TITLE
issue-203 Change :_content-type: to :_mod-docs-content-type:

### PR DESCRIPTION
**Pull request by emmurphy1**
I simply changed the variable name without explanation. After we merge this change, we will send out a detailed email explaining the reason for the change and options for updating repos that use this variable.

### CODE REVIEW

**Review by ncbaratta — APPROVED** [review]
lgtm

**Review by abhatt-rh — APPROVED** [review]
lgtm!

**Comment by Jenny-Anne** [comment]
lgtm too

**Comment by abhatt-rh** [comment]
> lgtm too

Hey @Jenny-Anne To record your approval for the PR, click Files changed > Review changes > Approve > Submit review. HTH!
image

**Review by Jenny-Anne — APPROVED** [review]

**Review by IanFrangs — APPROVED** [review]
LGTM

**Review by neal-timpe — APPROVED** [review]

**Review by thatdocslady — APPROVED** [review]

**Review by mjahoda — APPROVED** [review]

**Pull request merged**
